package deploy

import (
	"fmt"

	nomad "github.com/hashicorp/nomad/api"
)

// Zone is the DNS suffix every orca service answers under.
const Zone = "orca"

// DNSAddress is where the resolver listens: the gateway of Nomad's bridge.
//
// It is the one address every container on a machine can always reach and
// nothing outside the machine can reach at all, and unlike an allocation
// address it does not move when the resolver restarts — which matters because
// it is baked into every task's resolver configuration.
const DNSAddress = "172.26.64.1"

// dnsJob runs the cluster's resolver.
//
// It runs on the host's network rather than in a bridge namespace for two
// reasons: it has to bind the bridge gateway, which is not an address it would
// have from inside; and it forwards anything outside the orca zone to whatever
// the machine itself uses, which it reads from the host's resolver
// configuration.
func dnsJob(opts PlatformOptions) *nomad.Job {
	job, group, task := platformJob(opts, "dns", opts.Images.CoreDNS, 100, 128)

	// A system job: every machine needs a resolver it can reach locally, and
	// an allocation cannot use one across a network it may not be able to
	// route to.
	job.Type = ptr("system")

	task.Config["network_mode"] = "host"
	task.Config["args"] = []string{"-conf", "/local/Corefile"}

	task.Templates = append(task.Templates,
		&nomad.Template{
			EmbeddedTmpl: ptr(corefile()),
			DestPath:     ptr("local/Corefile"),
			ChangeMode:   ptr("restart"),
		},
		&nomad.Template{
			EmbeddedTmpl: ptr(dnsHosts()),
			DestPath:     ptr("local/hosts"),
			// noop, not restart: the hosts file changes every time any service
			// anywhere moves, and CoreDNS reloads it by itself. Restarting the
			// resolver each time would take name resolution away from the
			// whole machine for the sake of a file it was going to re-read.
			ChangeMode: ptr("noop"),
		},
	)

	group.Services = []*nomad.Service{{
		Name:     CatalogName(OrcaApp, "dns"),
		Provider: "nomad",
		Tags:     []string{DNSTag(OrcaApp, "dns")},
	}}
	job.Update.HealthCheck = ptr("task_states")
	return job
}

func corefile() string {
	// One server block for everything, with the hosts file consulted first and
	// falling through to the upstream resolver.
	//
	// Scoping the hosts file to the orca zone instead would mean a name like
	// "db.blog" — which is not under .orca — never reaching it, and being
	// forwarded upstream to fail. Every orca name is in the file, so trying
	// the file first costs a map lookup and answers all three spellings.
	//
	// The file's answers carry a 5s TTL rather than the plugin's default hour,
	// which the cache would have held for its full 30s: a copy being drained
	// has to stop being answered well inside DrainDelay.
	return fmt.Sprintf(`.:53 {
    bind %s
    hosts /local/hosts {
        reload 5s
        ttl 5
        fallthrough
    }
    forward . /etc/resolv.conf
    cache 30
}
`, DNSAddress)
}

// dnsHosts renders the resolver's hosts file from the service catalog: every
// registration carrying a DNS tag, at every address it has.
//
// The file changes whenever any service moves, and CoreDNS re-reads it on its
// own, so nothing about it is fixed at deploy time.
func dnsHosts() string {
	return fmt.Sprintf(`# generated by orca from the service catalog
{{- range nomadServices }}{{ $name := .Name }}{{ range .Tags }}{{ if . | regexMatch "^%[1]s" }}{{ $short := . | replaceAll "%[1]s" "" }}{{ range nomadService $name }}
{{ .Address }} {{ $short }}.%[2]s {{ $short }}{{ end }}{{ end }}{{ end }}{{ end }}
`, DNSTagPrefix, Zone)
}
