package main

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"regexp"
	"sort"
	"strings"

	"github.com/unitoftime/orca/internal/deploy"
	"github.com/unitoftime/orca/internal/manifest"
	"golang.org/x/term"
)

// `orca secret set`, `list`, `rm`, `export`, `import` and `edit`.
//
// Secrets live in Nomad's variable store on the cluster, and that is the only
// copy anything running reads. A deploy does not need secret values, because
// the value is read on the machine when the task starts. CI can therefore
// apply manifests without holding a single secret.
//
// The trade is that a rebuilt cluster has none. `export` writes them all to
// one file, encrypted to a passphrase, and `import` puts them back; see
// Bundle. The file is a copy to keep, never something apply reads.

// secretNamePattern is what a group or secret name may contain.
//
// Enforced rather than assumed: a secret's path is interpolated into a command
// that runs on the machine, so a name carrying shell metacharacters would run
// as that command. The operator is the only one who can supply one, which
// makes it their own machine they would be injecting into, but a name with a
// space in it silently doing the wrong thing is reason enough on its own.
// It matches manifest's secretName exactly. Otherwise a manifest could
// reference ${secret._token} and validate while `orca secret set blog/_token`
// is refused, leaving a secret that can never be set, and a purge that aborts
// on the same name it has just collected.
var secretNamePattern = regexp.MustCompile(`^[A-Za-z0-9_-]+$`)

// parseSecretRef splits and validates "<group>/<name>".
func parseSecretRef(ref string) (group, name string, err error) {
	group, name, ok := manifest.SplitRef(ref)
	if !ok {
		return "", "", fmt.Errorf("secret %q must be <group>/<name>, e.g. blog/session_key", ref)
	}
	for what, part := range map[string]string{"group": group, "name": name} {
		if !secretNamePattern.MatchString(part) {
			return "", "", fmt.Errorf(
				"secret %s %q may contain only letters, digits, dashes and underscores", what, part)
		}
	}
	return group, name, nil
}

// requiredSecrets is every secret the manifests reference, by group.
//
// There is no place to declare a secret: the references in the manifests are
// the declaration, so the list cannot drift from what is actually used.
func requiredSecrets(cfg Config) (map[string][]string, error) {
	groups, err := loadGroups(cfg)
	if err != nil {
		return nil, err
	}
	out := map[string][]string{}
	for _, m := range groups {
		// Generated secrets are included: the template wires them in directly,
		// so usage alone would leave the most important secret in a group
		// invisible. Deduplicated, because a generated secret is very often
		// also referenced: a database password is generated by its template
		// and then read by whatever connects to it.
		seen := map[string]bool{}
		var names []string
		for _, n := range append(m.Secrets(), m.GeneratedSecrets()...) {
			if !seen[n] {
				seen[n] = true
				names = append(names, n)
			}
		}
		if len(names) > 0 {
			sort.Strings(names)
			out[m.Group] = names
		}
	}
	return out, nil
}

func secretList(ctx context.Context, cfg Config, cluster *Cluster) error {
	required, err := requiredSecrets(cfg)
	if err != nil {
		return err
	}
	set, err := cluster.SecretPaths(ctx)
	if err != nil {
		return err
	}

	groups := make([]string, 0, len(required))
	for g := range required {
		groups = append(groups, g)
	}
	sort.Strings(groups)

	missing := 0
	for _, g := range groups {
		fmt.Println(g)
		for _, name := range required[g] {
			state := "set"
			if !set[deploy.SecretPath(g, name)] {
				state = "MISSING"
				missing++
			}
			fmt.Printf("  %-24s %s\n", name, state)
		}
	}

	// Anything in the store that nothing references any more. Not an error (a
	// secret outlives the service that used it often enough), but it should
	// not be invisible either.
	var orphans []string
	for path := range set {
		if !referenced(path, required) {
			orphans = append(orphans, path)
		}
	}
	sort.Strings(orphans)
	if len(orphans) > 0 {
		fmt.Println("\nset but not referenced by any manifest:")
		for _, p := range orphans {
			fmt.Printf("  %s\n", strings.TrimPrefix(p, deploy.SecretPrefix+"/"))
		}
	}

	if len(groups) == 0 && len(orphans) == 0 {
		fmt.Println("no secrets referenced or set")
	}
	if missing > 0 {
		fmt.Printf("\n%d secret(s) not set\n", missing)
	}
	return nil
}

func referenced(path string, required map[string][]string) bool {
	for g, names := range required {
		for _, n := range names {
			if deploy.SecretPath(g, n) == path {
				return true
			}
		}
	}
	return false
}

func secretSet(ctx context.Context, cfg Config, cluster *Cluster, ref string, force bool) error {
	group, name, err := parseSecretRef(ref)
	if err != nil {
		return err
	}
	if err := guardGenerated(cfg, []secretRef{{group, name}}, "change it", force); err != nil {
		return err
	}

	value, err := readSecretValue("value for " + ref)
	if err != nil {
		return err
	}
	if value == "" {
		return fmt.Errorf("refusing to set an empty secret")
	}

	if err := cluster.PutSecret(ctx, group, name, value); err != nil {
		return err
	}

	fmt.Printf("set %s\n", ref)

	// Nomad's template watches the variable, so any task using it restarts on
	// its own. Rotation is this command and nothing else. That is worth saying,
	// since the alternative assumption is that a redeploy is needed.
	if required, err := requiredSecrets(cfg); err == nil {
		for _, n := range required[group] {
			if n == name {
				fmt.Println("services using it will restart with the new value")
				return nil
			}
		}
		if group != manifest.ReservedGroup {
			fmt.Printf("note: no manifest references ${secret.%s} in group %q\n", name, group)
		}
	}
	return nil
}

// readSecretValue takes the value from stdin when it is piped, and prompts
// without echo when it is a terminal.
//
// It never comes from an argument: a command line is visible in the process
// table on both machines for as long as the command runs, and shell history
// keeps it long after.
//
// Piped input is read whole, not to the first newline: a PEM key, the spec's
// own example of a file secret, would otherwise be stored as its "-----BEGIN"
// line and nothing else. Only the trailing newline is dropped, which is what
// `echo token |` adds and never part of the value.
func readSecretValue(prompt string) (string, error) {
	if !term.IsTerminal(int(os.Stdin.Fd())) {
		return readPipedSecret(os.Stdin)
	}

	fmt.Fprintf(os.Stderr, "%s: ", prompt)
	raw, err := term.ReadPassword(int(os.Stdin.Fd()))
	fmt.Fprintln(os.Stderr)
	if err != nil {
		return "", fmt.Errorf("read value: %w", err)
	}
	return strings.TrimSpace(string(raw)), nil
}

func readPipedSecret(r io.Reader) (string, error) {
	raw, err := io.ReadAll(r)
	if err != nil {
		return "", fmt.Errorf("read value from stdin: %w", err)
	}
	return strings.TrimRight(string(raw), "\r\n"), nil
}

// guardGenerated refuses to change any secret orca generated unless forced.
//
// A generated database password is baked into the data directory the first
// time the database starts: Postgres reads POSTGRES_PASSWORD only then. Set
// it to something else and the database keeps the old one; remove it and the
// next apply generates a new one. Either way everything connecting is locked
// out, and the value nobody ever saw is gone. When the manifests do not load
// it cannot tell, so it refuses rather than guessing "not generated".
func guardGenerated(cfg Config, refs []secretRef, verb string, force bool) error {
	if force || len(refs) == 0 {
		return nil
	}
	groups, err := discoverGroups(cfg)
	if err != nil {
		return fmt.Errorf("cannot tell whether %v was generated by orca, because the manifests do not load "+
			"(re-run with --force if you are sure):\n%w", refs, err)
	}
	generated := map[secretRef]bool{}
	for _, g := range generatedSecrets(groups) {
		generated[g.secretRef] = true
	}
	var errs []error
	for _, r := range refs {
		if generated[r] {
			errs = append(errs, fmt.Errorf("%s was generated by orca for a template, and the service's data was initialised with it; "+
				"to %s would lock everything connecting out of that data.\n"+
				"re-run with --force if you have already changed it inside the service", r, verb))
		}
	}
	return errors.Join(errs...)
}

func secretRemove(ctx context.Context, cfg Config, cluster *Cluster, ref string, force bool) error {
	group, name, err := parseSecretRef(ref)
	if err != nil {
		return err
	}
	if err := guardGenerated(cfg, []secretRef{{group, name}}, "remove it", force); err != nil {
		return err
	}
	if err := cluster.DeleteSecret(ctx, group, name); err != nil {
		return err
	}
	fmt.Printf("removed %s\n", ref)
	return nil
}

// secretRef names one secret in the cluster's store.
type secretRef struct {
	Group string
	Name  string
}

func (r secretRef) Path() string   { return deploy.SecretPath(r.Group, r.Name) }
func (r secretRef) String() string { return r.Group + "/" + r.Name }

// neededSecrets is every secret an apply of these groups depends on: what
// their manifests reference, and the credentials of every target their
// backups write to.
//
// The credentials are the reason this is not just the manifests' own list. A
// target usually lives in another group (storage/offsite), so an apply
// scoped to the database's group would otherwise never look at them, and
// would deploy a backup job with no way to authenticate: the failure that
// only shows when a restore is needed.
func neededSecrets(groups []*manifest.Manifest, backups []backedUp) []secretRef {
	seen := map[secretRef]bool{}
	var out []secretRef
	add := func(r secretRef) {
		if !seen[r] {
			seen[r] = true
			out = append(out, r)
		}
	}
	for _, m := range groups {
		for _, n := range m.Secrets() {
			add(secretRef{m.Group, n})
		}
	}
	for _, b := range backups {
		add(secretRef{b.Spec.SecretGroup, b.Spec.KeyIDSecret})
		add(secretRef{b.Spec.SecretGroup, b.Spec.SecretKeySecret})
	}
	return out
}

// checkMissing reports any needed secret that is not set.
//
// Apply calls this before touching the cluster. Without it the failure
// surfaces as Nomad blocking the task on a missing variable, which means
// waiting out the health timeout to be told a raft path is missing rather
// than which secret to go and set.
func checkMissing(needed []secretRef, set map[string]bool) error {
	var missing []string
	for _, r := range needed {
		if !set[r.Path()] {
			missing = append(missing, r.String())
		}
	}
	if len(missing) == 0 {
		return nil
	}
	sort.Strings(missing)

	return errors.New("these secrets are referenced but not set:\n  " +
		strings.Join(missing, "\n  ") +
		"\n\nset them with: orca secret set <group>/<name>")
}

// generatedSecretLength is long enough that the value is not worth attacking
// and short enough to paste when something needs it by hand.
const generatedSecretLength = 32

// secretAlphabet avoids punctuation on purpose. A generated password ends up
// inside a connection string more often than not, and one containing a "/" or
// an "@" turns a working URL into a confusing parse error.
const secretAlphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

// generateSecret returns a new random value in the shape the template asked
// for.
//
// A format rather than one universal string, because some of these are not
// orca's to choose: Garage will not accept an access key id that is not "GK"
// and 24 hex characters, or an RPC secret that is not 32 bytes of hex.
func generateSecret(spec manifest.GeneratedSecretSpec) (string, error) {
	n := spec.Bytes
	if n == 0 {
		n = generatedSecretLength
	}

	buf := make([]byte, n)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("generate secret: %w", err)
	}

	if spec.Hex {
		return spec.Prefix + hex.EncodeToString(buf), nil
	}

	out := make([]byte, n)
	// Modulo bias is negligible here: 62 into 256 leaves the first eight
	// values very slightly favoured, which does not meaningfully reduce the
	// search space of a 32-character value.
	for i, b := range buf {
		out[i] = secretAlphabet[int(b)%len(secretAlphabet)]
	}
	return spec.Prefix + string(out), nil
}

// generatedSecret is one secret a template owns.
type generatedSecret struct {
	secretRef
	spec manifest.GeneratedSecretSpec

	// service is the one it is generated for.
	service string
}

// generatedSecrets is every secret orca creates for these groups' templates.
func generatedSecrets(groups []*manifest.Manifest) []generatedSecret {
	var out []generatedSecret
	for _, m := range groups {
		for _, s := range m.Services {
			t := s.Tmpl()
			if t == nil {
				continue
			}
			for _, sec := range t.Spec().Secrets {
				out = append(out, generatedSecret{
					secretRef: secretRef{m.Group, manifest.GeneratedSecret(s.Name, sec.Suffix)},
					spec:      sec,
					service:   s.Name,
				})
			}
		}
	}
	return out
}

// createGeneratedSecrets creates the secrets a template owns that do not
// exist yet.
//
// It only ever creates: a value that already exists is left alone, because
// regenerating a database password on every apply would lock the database out
// of itself. The best secret is one nobody handles, and this is what makes a
// templated database need no setup at all.
func createGeneratedSecrets(ctx context.Context, cluster *Cluster, want []generatedSecret) error {
	for _, g := range want {
		value, err := generateSecret(g.spec)
		if err != nil {
			return err
		}
		created, err := cluster.CreateSecret(ctx, g.Group, g.Name, value)
		if err != nil {
			return err
		}
		if !created {
			// Something created it between the check and now. Its value is
			// the one to keep, which is exactly what create-only guarantees.
			fmt.Printf("secret %s already exists; kept\n", g)
			continue
		}
		fmt.Printf("generated secret %s\n", g)
	}
	return nil
}
